### ISSUE TITLE
...

### ISSUE THREAD

**Issue by CsirtEntelgy** [fdcrespi/TPETd-v#1]

**Comment by gangstertoppen** [comment]
§107. Limitations on exclusive rights: Fair use

Notwithstanding the provisions of sections 106 and 106A, the fair use of a copyrighted work, including such use by reproduction in copies or phonorecords or by any other means specified by that section, for purposes such as criticism, comment, news reporting, teaching (including multiple copies for classroom use), scholarship, or research, is not an infringement of copyright. In determining whether the use made of a work in any particular case is a fair use the factors to be considered shall include-
(1) the purpose and character of the use, including whether such use is of a commercial nature or is for **nonprofit educational** purposes;
(2) the nature of the copyrighted work;
(3) the amount and substantiality of the portion used in relation to the copyrighted work as a whole; and
(4) the effect of the use upon the potential market for or value of the copyrighted work.

A very small portion of this users work is "infringing". You can´t claim that it is just because the user is referring to Santander a couple times in their code.

**Comment by CsirtEntelgy** [comment]
..
